TEXTS = {
    "tr": {
        "choose_language": "Lütfen dilinizi seçin:",
        "welcome": "🎯 *Hoş geldin, {name}!*\n\nBen **Statify Bet AI** – yapay zeka destekli futbol tahmin botuyum.\nGünlük maçları istatistiksel modellerle analiz ediyor, kazanan takım, her iki takımın gol atması (KG) ve toplam gol sayısı (Üst/Alt) gibi ana piyasalara yönelik tahminler sunuyorum.\n\n📊 *Başarı Oranımız:* %%92\n✅ Tüm tahminler veriye dayalıdır.",
        "menu_prompt": "Ana menüden bir seçenek belirleyin:",
        "menu_tips": "📊 Tahminler",
        "menu_history": "📜 Geçmiş",
        "menu_vip": "⭐ VIP",
        "menu_support": "🆘 Destek",
        "menu_language": "🌐 Dil",
        "tips_title": "📊 Bugünün Tahminleri (Normal):\nAşağıdan bir maç seçin.",
        "no_matches": "⚠️ Henüz bu kategoride tahmin eklenmemiş.",
        "back": "◀️ Geri",
        "match_not_found": "Maç bulunamadı.",
        "history_text": "📜 *Geçmiş maçlar:*\n{matches}",
        "no_history": "Henüz geçmiş maç bulunmuyor.",
        "support_prompt": "🆘 Destek ekibimize mesaj göndermek için aşağıya yazabilirsiniz.\nMesajınız 1-24 saat içinde cevaplandırılacaktır.",
        "support_thanks": "✅ Mesajınız alındı. En kısa sürede (1-24 saat) size dönüş yapılacaktır.",
        "support_reply": "📩 Destek ekibinden yanıt:\n\n{reply_text}",
        "admin_notify": "📩 Yeni destek mesajı!\nKullanıcı: {user}\nMesaj: {msg}",
        "error_generic": "Bir hata oluştu, lütfen tekrar deneyin.",
        "add_match_info": "📅 Maçın adını ve tarihini gönderin (örnek: 30.08 Barca - Real Madrid):",
        "add_match_prediction_stats": "📊 Tahmin ve istatistik metnini birlikte gönderin:",
        "add_match_category": "🗂️ Bu tahmini hangi kategoriye ekleyelim?",
        "category_normal": "📊 Normal",
        "category_vip": "⭐ VIP",
        "match_added": "✅ Maç uğurla əlavə edildi! ID: {match_id}",
        "match_deleted": "✅ Maç silindi.",
        "match_list": "📋 Mevcut maçlar:\n{list}",
        "no_matches_list": "Henüz maç yok.",
        "admin_denied": "❌ Bu komutu yalnız admin kullanabilir.",
        "delete_match_usage": "Kullanım: /deletematch <match_id>",
        "reply_usage": "Kullanım: /reply <ticket_id> <cevap>",
        "vip_active_status": "⭐ *VIP üyeliğiniz aktif!*\n\n🗓 Bitiş tarihi: {expiry}\n\nVIP tahminlere bakabilir veya süreyi uzatabilirsiniz:",
        "vip_intro": "⭐ *VIP Üyelik*\n\nVIP üyeler için özel tahminler ve analizler edinin!\nTelegram Stars ile ödeme yaparak hemen aktifleştirin 👇",
        "vip_tips_button": "📊 VIP Tahminlere bak",
        "vip_tips_title": "⭐ *VIP Tahminler:*",
        "no_vip_matches": "⚠️ Şu anda VIP tahmin yok.",
        "vip_denied": "❌ VIP üyeliğiniz yok veya süresi bitti.",
        "plan_not_found": "❌ Plan bulunamadı.",
        "invoice_description": "{days} gün boyunca VIP tahminlere erişim",
        "payment_error": "❌ Ödemede bir hata oluştu. Lütfen adminle iletişime geçin: @kamrancmlv",
        "payment_success": "✅ *Ödeme başarıyla tamamlandı!*\n\n⭐ {plan} aktifleştirildi.\n🗓 Bitiş tarihi: {expiry}\n\nArtık VIP tahminlere bakabilirsiniz!",
    },
    "en": {
        "choose_language": "Please select your language:",
        "welcome": "🎯 *Welcome, {name}!*\n\nI am **Statify Bet AI** – an AI-powered football prediction bot.\nI analyze daily matches using statistical models and provide tips for Match Winner, BTTS, and Over/Under goals.\n\n📊 *Success Rate:* 92%%\n✅ All predictions are data-driven.",
        "menu_prompt": "Choose an option from the main menu:",
        "menu_tips": "📊 Tips",
        "menu_history": "📜 History",
        "menu_vip": "⭐ VIP",
        "menu_support": "🆘 Support",
        "menu_language": "🌐 Language",
        "tips_title": "📊 Today's Tips (Normal):\nSelect a match below.",
        "no_matches": "⚠️ No predictions in this category yet.",
        "back": "◀️ Back",
        "match_not_found": "Match not found.",
        "history_text": "📜 *Past matches:*\n{matches}",
        "no_history": "No past matches yet.",
        "support_prompt": "🆘 Write your message to our support team below.\nYour message will be replied within 1-24 hours.",
        "support_thanks": "✅ Your message has been received. We will reply within 1-24 hours.",
        "support_reply": "📩 Support team reply:\n\n{reply_text}",
        "admin_notify": "📩 New support message!\nUser: {user}\nMessage: {msg}",
        "error_generic": "An error occurred, please try again.",
        "add_match_info": "📅 Send match name and date (e.g. 30.08 Barca - Real Madrid):",
        "add_match_prediction_stats": "📊 Send prediction and stats text together:",
        "add_match_category": "🗂️ Which category to add this tip to?",
        "category_normal": "📊 Normal",
        "category_vip": "⭐ VIP",
        "match_added": "✅ Match successfully added! ID: {match_id}",
        "match_deleted": "✅ Match deleted.",
        "match_list": "📋 Current matches:\n{list}",
        "no_matches_list": "No matches yet.",
        "admin_denied": "❌ This command is for admin only.",
        "delete_match_usage": "Usage: /deletematch <match_id>",
        "reply_usage": "Usage: /reply <ticket_id> <reply>",
        "vip_active_status": "⭐ *Your VIP membership is active!*\n\n🗓 Expires on: {expiry}\n\nYou can view VIP tips or extend your membership:",
        "vip_intro": "⭐ *VIP Membership*\n\nGet exclusive tips and analysis for VIP members!\nPay with Telegram Stars to activate instantly 👇",
        "vip_tips_button": "📊 View VIP Tips",
        "vip_tips_title": "⭐ *VIP Tips:*",
        "no_vip_matches": "⚠️ No VIP tips available right now.",
        "vip_denied": "❌ You don't have an active VIP membership.",
        "plan_not_found": "❌ Plan not found.",
        "invoice_description": "{days}-day access to VIP tips",
        "payment_error": "❌ There was an error processing your payment. Please contact the admin: @kamrancmlv",
        "payment_success": "✅ *Payment completed successfully!*\n\n⭐ {plan} activated.\n🗓 Expires on: {expiry}\n\nYou can now view VIP tips!",
    }
}
